spring:
  datasource:
    url: jdbc:mysql://fimgcserver.mysql.database.azure.com:3306/dbfimgc
    username: junior
    password: contrasena:FIMGC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 150MB
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect           
  mail:
    host: smtp.gmail.com
    port: 587
    username: eliu.anaya.27@unsch.edu.pe
    password: Tresagostoanayita5
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  
            
documentos:
    expedientes:
      dir: documentos/Expedientes/ 

